apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordersapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnetcoreapp
        component: ordersapi
    spec:
      containers:
      - name: ordersapi
        image: acrgirish.azurecr.io/knowzy/ordersapi:__buildId__
        env:
        - name: COSMOSDB_ENDPOINT
          value: https://devopsmeetupcosmosdb.documents.azure.com:443
        - name: COSMOSDB_KEY
          value: "ZbeHgqDG9dZLfv3rDh9mHDXYigF7Tw9Iro3tC3hqqdJIlbvSv6svATkQxXIVrjEWaSCDLhH6yA2QXPYyRjhdWQ=="
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productsapi 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnetcoreapp
        component: productsapi 
    spec:
      containers:
      - name: productsapi 
        image: acrgirish.azurecr.io/knowzy/productsapi:__buildId__
        env:
        - name: COSMOSDB_ENDPOINT
          value: https://devopsmeetupcosmosdb.documents.azure.com:443
        - name: COSMOSDB_KEY
          value: "ZbeHgqDG9dZLfv3rDh9mHDXYigF7Tw9Iro3tC3hqqdJIlbvSv6svATkQxXIVrjEWaSCDLhH6yA2QXPYyRjhdWQ=="
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnetcoreapp
        component: webapp 
    spec:
      containers:
      - name: webapp 
        image: acrgirish.azurecr.io/knowzy/webapp:__buildId__
        env:
        - name: ORDERSAPI_URL
          value: http://10.0.0.17
        - name: PRODUCTSAPI_URL
          value: http://10.0.0.18
      imagePullSecrets:
      - name: myregistrykey
