apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetcoreapp
    component: ordersapi 
  name: ordersapi 
spec:
  ports:
  - port: 80
  selector:
    app: dotnetcoreapp
    component: ordersapi 
    type: LoadBalancer
    load-balancer-ip: '1.2.3.4'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetcoreapp
    component: productsapi 
  name: productsapi 
spec:
  ports:
  - port: 80
  selector:
    app: dotnetcoreapp
    component: productsapi 
    type: LoadBalancer
    load-balancer-ip: '5.6.7.8'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetcoreapp
    component: webapp 
  name: webapp 
spec:
  ports:
  - port: 80
  selector:
    app: dotnetcoreapp
    component: webapp
  type: LoadBalancer


