apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetcoreapp
    component: ordersapi 
  name: ordersapi 
spec:
  ports:
  - port: 80
  selector:
    app: dotnetcoreapp
    component: ordersapi 
  clusterIP: 10.0.0.17
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetcoreapp
    component: productsapi 
  name: productsapi 
spec:
  ports:
  - port: 80
  selector:
    app: dotnetcoreapp
    component: productsapi
  clusterIP: 10.0.0.18
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnetcoreapp
    component: webapp 
  name: webapp 
spec:
  ports:
  - port: 80
  selector:
    app: dotnetcoreapp
    component: webapp
  type: LoadBalancer


